feat(resources): support for camunda cluster clients
multani/terraform-provider-camunda pull request #13
Opened 2022-07-08 22:23 UTC by Sijoma

Support for cluster clients. 

Console seems to also support renaming the name of the client in-place. However this is not reflected in the external api afaik. 
https://console.cloud.camunda.io/customer-api/openapi/docs/#/

<img width="944" alt="image" src="https://user-images.githubusercontent.com/8970764/178077376-38710674-5c40-4a97-8b86-deca6fb56788.png">

2022-07-11 20:09 UTC, Sijoma commented on internal/provider/camunda_cluster_client_resource.go
> +			},
Thanks for the link. I played a bit with it and added the length validator (1-50 characters). Also a "no spaces validator". 

I'm not sure if a RegExp validator would be better (or more common). I did not like that route as it reduces readability sometimes and its harder to combine them as you always have to make sure what the regexp really matches. 

I would keep it at that for this PR.

2022-07-11 20:10 UTC, Sijoma commented on internal/provider/camunda_cluster_client_resource.go
> +
Makes sense. Should I remove the values for now or can we leave that in for the merge and do the required changes later?

2022-07-12 06:04 UTC, multani commented on internal/provider/camunda_cluster_client_resource.go
> +
Either we don't expose these values at all, or we need to add a read after the creation to fetch the missing data.

Having modification in the plan, just after an initial `terraform apply`, is a bug usually.

2022-07-12 06:16 UTC, multani commented on internal/provider/camunda_cluster_client_resource.go
> +			},
We'll probably have to rewrite it to a regex soon anyway, I guess spaces are not the only invalid characters for a client name.

2022-07-12 19:04 UTC, Sijoma commented
I've added the second client read operation. It works with an existing cluster. Some request seems to fail when the cluster is not yet created. Maybe we can merge the change you did for the wait until the cluster is created?

2022-07-13 13:18 UTC, multani commented
Worked nicely with the changes from master :tada:

2022-07-13 13:18 UTC, multani approved these changes

2022-07-13 13:20 UTC, multani requested changes

2022-07-13 13:20 UTC, multani commented on internal/provider/camunda_cluster_client_resource.go
> +	}
```suggestion
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to fetch client details",
			fmt.Sprintf("Unable to fetch client details, got error got error: %s",
				err.(*console.GenericOpenAPIError).Body()))
		return
	}
```

2022-07-18 11:14 UTC, merged